-- Phase 2 of tournaments: pool play.
--
-- A category gets divided into N pools (e.g. 16 teams → 4 pools of 4)
-- via snake seeding by combined player rating, then each pool plays
-- round-robin. Top X from each pool (advance_per_pool) advance to the
-- bracket later (phase 3).
--
-- Schema notes:
--   • tournament_pools — one row per pool (Pool A, B, C, D…) tied to a
--     category. Letter is generated by the seeder, sort_order keeps the
--     UI stable.
--   • teams gains pool_id (assignment) + seed (overall, 1..N within
--     the category) + pool_seed (1..pool_size within the pool).
--   • games is the actual schedule. Pool games carry a pool_id; bracket
--     games (next phase) will leave it null and use stage='qf'/'sf'/'f'.
--     team_a_id/team_b_id are nullable so bracket games can be created
--     before they have known competitors.
--
-- Court assignment is decided at generation time; the pool/bracket
-- generator either pins each pool to a single court (when pool_count
-- ≤ court_count, the typical case) or rotates evenly. Per-category
-- semifinals_court_id / finals_court_id (existing) override for
-- showcase rounds.

create table public.tournament_pools (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.tournament_categories(id) on delete cascade,
  letter text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (category_id, letter)
);

create index tournament_pools_category_id_idx on public.tournament_pools(category_id);

alter table public.teams
  add column if not exists pool_id uuid references public.tournament_pools(id) on delete set null,
  add column if not exists seed int,
  add column if not exists pool_seed int;

create index if not exists teams_pool_id_idx on public.teams(pool_id);

create table public.games (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.tournament_categories(id) on delete cascade,
  pool_id uuid references public.tournament_pools(id) on delete cascade,
  stage text not null check (stage in ('pool', 'qf', 'sf', 'f')),
  round int not null,
  court_id uuid references public.tournament_courts(id) on delete set null,
  team_a_id uuid references public.teams(id) on delete set null,
  team_b_id uuid references public.teams(id) on delete set null,
  score_a int check (score_a is null or score_a >= 0),
  score_b int check (score_b is null or score_b >= 0),
  winner_team_id uuid references public.teams(id) on delete set null,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  starts_at timestamptz,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index games_category_id_idx on public.games(category_id);
create index games_pool_id_idx on public.games(pool_id);
create index games_court_id_idx on public.games(court_id);
create index games_status_idx on public.games(status);

create trigger games_set_updated_at
before update on public.games
for each row execute function public.set_updated_at();

alter table public.tournament_pools enable row level security;
alter table public.games enable row level security;

create policy "tournament_pools: public read"
on public.tournament_pools for select
to anon, authenticated
using (true);

create policy "games: public read"
on public.games for select
to anon, authenticated
using (true);

-- Service role bypasses RLS for writes.
